### ISSUE TITLE
Adding a workbook template for Mezzurite

### ISSUE THREAD

**Issue by JerryBlake** [Microsoft/Application-Insights-Workbooks#100]
Hi,
We been working on a Ai Workbook template to show the data generated from the https://github.com/Microsoft/ApplicationInsights-JS-Mezzurite plugin.  We have our template but need to know where to check it into.  The data is sent up via the pageviewperformance method, and shows up in the browser timings folder.

**Comment by jpiyali** [comment]
@ericc1103 - can you please recommend a folder for the mezzurite extension workbook to go under?

**Comment by ericc1103** [comment]
@JerryBlake Please create your workbook folder under `Application-Insights-Workbooks/Workbooks/`
As an example, feel free to take a look at folders called `Virtual Machines` or `Virtual Machines (Classic)`

**Comment by gardnerjr** [comment]
see #120 for a PR that has this template.
