### ISSUE TITLE
Multi Cluster Performance: Average Cluster CPU/Mem Utilization

### ISSUE THREAD

**Issue by rafa-pizzi** [microsoft/Application-Insights-Workbooks#1007]
heWhen switching metrics from CPU->Mem the hive dashboard (Average Cluster <metric> utilization % by nodepool)  does not change. It only always shows the same value on the hive.
There is also something wrong with the nodepool names, if you have more than one nodepool.
All my linux nodepools (which naturally have other names rather than "default" )are shown as default. So I end up with 3 "default" nodepools in my cluster

**Comment by pizzaz93** [comment]
@austonli does https://github.com/microsoft/Application-Insights-Workbooks/commit/3327e16829e964dcbfa23f28c2e0a71785fb02f5 resolve this issue?
