### ISSUE TITLE
Parameters in Metrics

### ISSUE THREAD

**Issue by AndrewSmithRS** [microsoft/Application-Insights-Workbooks#1155]
Is it currently possible to use parameters to populate metric settings? I can choose a parameter for the Metric (e.g. using cpu_percent) however even though the parameter seems to be correct I'm unable to select an Aggregation. I'm not clear how this would work with multiple parameters either.

I was attempting to duplicate the functionality of Database Resource Utilization in Azure SQL Elastic Pools.

**Comment by gardnerjr** [comment]
@ericajlin can comment on the things that support parameters in metrics.

**Comment by ericajlin** [comment]
Hi @AndrewSmithRS, 
Yes, metrics can be used with parameters. To do this, your parameter value needs to be the full metric ID. For example, the metric ID for storage account availability metric is `microsoft.storage/storageaccounts-Transaction-Availability`.

The easiest way to get the metric ID is the following:
1. Using the regular metric pill control, pick the metric(s) you are interested in
2. View the results in `Grid` visualization format
3. Switch the `Format` option to `Row per Metric`
4. Copy the metric ID under the `Metric ID` column
5. Use this metric ID value in your parameter, and reference your parameter in the metric drop down picker

Hope this helps!

**Comment by ericajlin** [comment]
Closing this issue, please re-open if necessary.
