### ISSUE TITLE
Private Workbooks Deprecation Jul 2021

### ISSUE THREAD

**Issue by bbbbbbbs** [microsoft/Application-Insights-Workbooks#1267]
Hello, can this work be put on hold please?

-  “Save as private workbook” is quite useful,  and we would like it to remain. 
Test workbooks will fill up the shared area unnecessary otherwise.
Probably better to provide a choice instead of removing it completely. 

-  The git doc does not explain the reason for this change or value (2nd time the document is published, first one in November).

- No explanation on role changes for users and work required for admins.

-	It seems a user role for the update to workbooks as a whole does not exist. Can a document on workbook access be created please?   

Thanks

**Comment by gardnerjr** [comment]
Working with PM and @tonykslee to update the docs with better explanations.

Removing private workbooks simplifies a lot of confusing experiences and support issues that customers are having with private workbooks compared to full Azure Resource based Workbooks.  

The simplest way to keep things separate is to save test workbooks to other subscriptions or resource groups.  An upcoming change to the workbook gallery will make it easier to filter to specific resource groups to filter to specific resource groups.

There are existing documents about workbook  Access control here:
https://docs.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-access-control

There are no changes to the behaviors of roles, or access control with these changes.
