### ISSUE TITLE
Validation test should catch improper JSON dropdown

### ISSUE THREAD

**Issue by andrewki-msft** [Microsoft/Application-Insights-Workbooks#130]
Validation test should fail when dropdown has improperly formatted JSON or else the dropdown will not show anything.
![image](https://user-images.githubusercontent.com/43890980/53601069-0b0fe100-3b60-11e9-8dfe-20409fe26da0.png)

**Comment by acearun** [comment]
@gardnerjr can we notify the user about this error on parameter save?

**Comment by gardnerjr** [comment]
ideally when you press update, yes.  the preview dropdown would already be empty after that as well.  

since this is on the extension code side, I've opened

> Bug  4223101: Workbooks: invalid json should prevent saving parameter

there, and will close this item here.
