### ISSUE TITLE
how do we use these?

### ISSUE THREAD

**Issue by abelal83** [microsoft/Application-Insights-Workbooks#1381]
Sorry if I missed the obvious but how are we able to use these workbooks? I went to "Azure monitor > workbooks > public templates" but I can't find the majority of these there. Any help much appreciated.

**Comment by Aaronontheweb** [comment]
Same - I can't figure out how I'm supposed to deploy my own custom workbook templates either. The ARM template that gets generated from the resource doesn't include the Workbook gallery definition.

**Comment by Aaronontheweb** [comment]
Looks like there's a guide for deploying these here: https://docs.microsoft.com/en-us/azure/azure-monitor/visualize/workbooks-automate

**Comment by abelal83** [comment]
I have to be honest it's rather long winded, these workbook look really great but I wish it was simple to use.

**Comment by Aaronontheweb** [comment]
Agree - it took hours for me to find that and I have to find a way to make it so our customers can replicate this process also and import this workbook into their own subscriptions.

**Comment by Aaronontheweb** [comment]
Even deploying a template via that guide doesn't work - after a successful ARM deployment the templates don't show up under "My Templates" in Azure Monitor

**Comment by abelal83** [comment]
I tried also, managed to import one in but it simply doesn't work. None the drop down list any resources.

**Comment by yves-chan** [comment]
Hi @abelal83 and @Aaronontheweb 
> Sorry if I missed the obvious but how are we able to use these workbooks? I went to "Azure monitor > workbooks > public templates" but I can't find the majority of these there. Any help much appreciated.

These workbook templates are spread across different galleries in the Azure portal. The Azure Monitor gallery is just one of them. Workbooks that show up on Azure Monitor will be in the gallery/workbook/Azure Monitor.json. In there, you'll find there are workbook ids which are the paths that correspond to the templates in this repo. You can search for the template id to find the gallery for a specific workbook template.

> Even deploying a template via that guide doesn't work - after a successful ARM deployment the templates don't show up under "My Templates" in Azure Monitor

In the Azure portal, there is a 'Azure Workbooks' browse view, are you able to see your template resource there? When deploying, if the type is `workbook` and the resourceType is `Azure Monitor`, your template should show up in the Azure Monitor Gallery. Please open a separate issue if this is not the case and we can look into it further

> I tried also, managed to import one in but it simply doesn't work. None the drop down list any resources.

Which template were you trying to import? and what were the steps taken?

**Comment by BMichaelJ** [comment]
Hi @yves-chan 
Not really following where to find the json "gallery/workbook/Azure Monitor.json"
Could you elaborate? 
Thanks

**Comment by yves-chan** [comment]
Hi @BMichaelJ

I was referring to this file: https://github.com/microsoft/Application-Insights-Workbooks/blob/master/gallery/workbook/Azure%20Monitor.json

You'll notice in this json file, in the templates array which has workbook entries. The id field corresponds to the workbook in this repository. ie: `"id": "Workbooks/Virtual Machines/At-scale Metrics"` is the workbook https://github.com/microsoft/Application-Insights-Workbooks/tree/master/Workbooks/Virtual%20Machines/At-scale%20Metrics
