### ISSUE TITLE
Connections workbook doesn't support custom time range

### ISSUE THREAD

**Issue by andrewki-msft** [Microsoft/Application-Insights-Workbooks#146]
Connections workbook doesn't support custom time range
![image](https://user-images.githubusercontent.com/43890980/54386699-d10e0700-4656-11e9-98f4-ef025ec7353b.png)

**Comment by acearun** [comment]
The issue happens because you are running this query:

> print("let computers = ServiceMapComputer_CL | where TimeGenerated {TimeRange} | summarize (TimeGenerated, Properties) = arg_max(TimeGenerated, pack_all()) by Computer;");

For custom time ranges, the time range expands to something like:

> between(datetime("2019-03-14T04:12:00.000Z")..datetime("2019-03-15T04:12:00.000Z"))

Since both strings use double quotes, it messes up the string you are trying to print. The fix is to use a single quote for your print string

> print('let computers = ServiceMapComputer_CL | where TimeGenerated {TimeRange} | summarize (TimeGenerated, Properties) = arg_max(TimeGenerated, pack_all()) by Computer;');

**Comment by acearun** [comment]
A better practice is not use time parameters in KQL but instead bind it to the Time Range drop down of the parameters:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/9730127/54408644-cdeb3900-469f-11e9-9bfa-c50a671fb21e.png">

In this case, workbooks will take care of setting up your time context. Less chance of running into issues like this one.

**Comment by acearun** [comment]
@andrewki-msft can you confirm if the suggestion works and close this issue please?

**Comment by andrewki-msft** [comment]
> @andrewki-msft can you confirm if the suggestion works and close this issue please?

Yes, will push out a fix soon
