### ISSUE TITLE
M35911: Ambiguity: Please, explain what "from the box" means

### ISSUE THREAD

**Issue by v-makoud** [Microsoft/Application-Insights-Workbooks#148]
Hello @ericc1103,
Translator has reported possible source content issue.
Link to Github file: https://github.com/Microsoft/Application-Insights-Workbooks/blob/master/Workbooks/TSG/Performance%20Counter%20TSG/Performance%20Counter%20TSG.workbook
Row where the issue is located: 217
Comment: Translator asks to confirm the meaning of "serviced from the box" here, since they could not find a definition for this expression.

Can you please review the comment and provide answer/explanation? Also, if source fix is needed please provide link to the PR that will include the fix, so we can confirm and close this Issue.
Many thanks in advance.

**Comment by acearun** [comment]
```
Other possible reasons include: ...**too many web apps being serviced from the box**...
```

Replacing this section with:

```
Other possible reasons include: 
1. Frequent jobs or scheduled tasks on the machine, 
2. Excessive modules/plugins/extensions,
3. Too many web apps running on the underlying compute resources,
4. Search engine spiders and bots.
```
It was meant to mean - there may be many other apps running on the same compute instance, possibly slowing down the current app.

Hopefully, this clarifies things.
