### ISSUE TITLE
Cannot load Deprecated Workbook Retrieval Tool correctly

### ISSUE THREAD

**Issue by kozloffj** [microsoft/Application-Insights-Workbooks#1562]
Hi!
I am trying to run the Deprecated Workbook Retrieval Tool as described here - https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/LegacyAI/DeprecatedWorkbookRetrievalTool.md. 

When I try to load it in a new Workbook, I get an error. After further review, there are unnecessary double quotes in some locations. After I removed the double quotes (Using Visual Studio Code) it loads. After selecting a Subscription and Resource Group though, another section has an error where it says an API parameter must be added and the Subscription path was not passed. I added the subscription path manually and a API, but nothing else loads.

Can you take a look please?

Thank you,
Jeff Kozloff

**Comment by kozloffj** [comment]
Here is the updated JSON with the extra double quotes removed.

[UpdatedWorkbookRetrievalTool.txt](https://github.com/microsoft/Application-Insights-Workbooks/files/6916604/UpdatedWorkbookRetrievalTool.txt)

**Comment by darthkurak** [comment]
Have the exactly same problem. I would like to retrieve deprecated workbooks (shared), but scripts doesn't work.

**Comment by gardnerjr** [comment]
how *exactly* are you using the files that you're getting errors?

1) open a new empty workbook
    * from azure monitor for private workbooks, 
    * from the app insights resource for legacy workbooks
    
2) go into edit mode, and advanced mode

3) open the correct file from github, in *raw* mode, so you only have the workbook content, for example
    * private - https://raw.githubusercontent.com/microsoft/Application-Insights-Workbooks/master/Documentation/LegacyAI/PrivateWorkbookConversion.workbook
    * legacy - https://raw.githubusercontent.com/microsoft/Application-Insights-Workbooks/master/Documentation/LegacyAI/LegacyWorkbookConversion.workbook

4) paste that into advanced mode JSON box in workbooks, 
5) press apply

when i do this i see no issues.  is there some other set of steps you are doing that gets extra quotes?

**Comment by kozloffj** [comment]
Hi @gardnerjr !
Thanks for the follow-up. The links you provided just worked. The difference is:

I go to this page in Github - https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/LegacyAI/DeprecatedWorkbookRetrievalTool.md

I click on Private Workbook Conversion link
![image](https://user-images.githubusercontent.com/26456745/127916035-b41dadc7-780f-4f91-a79b-a549298ea1e2.png)

When I do this, I copy the code form that screen and paste it into the editor, I get the following failure -

![image](https://user-images.githubusercontent.com/26456745/127916176-712329ba-53a1-42d9-a08d-681f103ed36d.png)

HOWEVER, if I use the Raw links you provided above, I get no error. Not sure why they are different but maybe you can link to the raw links you listed in your reply above instead in the md file and that will help others.

Thanks!

Jeff Kozloff

**Comment by kozloffj** [comment]
Just to clarify, this is the screen that causes errors in the JSON -
![image](https://user-images.githubusercontent.com/26456745/127918080-e044054f-a857-426b-b25f-2d491913583e.png)

Need to click on "Raw" button for proper format -
![image](https://user-images.githubusercontent.com/26456745/127918198-55a54d5f-7ce6-4db8-a28c-294ec64f63b7.png)

Hope this helps others!

Thanks!
Jeff

**Comment by gardnerjr** [comment]
yes, the screen that you see in github's normal view is rendering the workbook json as text/markdown, so if you copy/paste from there strange things can happen.  you need to go to the raw view explicitly.

**Comment by gardnerjr** [comment]
@tonykslee can you update the instructions to give the literal instructions (or links?) for the raw files instead of just "(raw)" in parens? see my explicit instructions above that unblocked/clarified here.
