### ISSUE TITLE
travis validation build is no longer running? (and document here in this repo how it is configured)

### ISSUE THREAD

**Issue by gardnerjr** [microsoft/Application-Insights-Workbooks#183]
not sure how/why/when it stopped running but it isn't running anymore.

**Comment by ericc1103** [comment]
This is the one of the latest PR and I do see travis validation build ran:

![image](https://user-images.githubusercontent.com/5156022/57487807-4caabf80-7266-11e9-855c-3d2fcf0050d1.png)

**Comment by gardnerjr** [comment]
here's one that completed and didn't run CI:
![image](https://user-images.githubusercontent.com/10158007/57492245-f7c27580-7274-11e9-99f7-ffd8d76a0e0f.png)

**Comment by gardnerjr** [comment]
there needs to be documentation somewhere here in this repo that explains how travis is configured for builds here, what triggers it, and why some file changes/branches aren't getting CI builds?

**Comment by gardnerjr** [comment]
what I've found so far.  
* travis is configured with a `.travis.yml` file in the root of the repo
* https://travis-ci.org/microsoft/Application-Insights-Workbooks  is where the builds show up 
* but they somehow aren't always showing up linked to the PR/commits here?

**Comment by gardnerjr** [comment]
as of #309 i have the travis.yml set up to always build master when it gets updated, AND to build any PR branches as PR builds.  the rest of the info is above.  i'm still not sure why it stopped working and then started working again, though.
