### ISSUE TITLE
Creating a workbook instance for an application insight programmatically

### ISSUE THREAD

**Issue by NandiniGV** [microsoft/Application-Insights-Workbooks#190]
We have a workbook created manually for an application insight and I am trying to deploy workbook instance to application insight using the arm template. ARM template was copied from the portal , by going to the advanced settings of workbook in an edit mode.
 But, when deployed the arm template using PowerShell or even used visual studio, it is deploying like a individual resource in the resource group and not getting associated to the application insight. 

I did check this sample arm template mentioned here : https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Programmatically.md 

Workbook types I tried using 'tsg' as suggested and also type 'workbook' , but both of these are not getting associated to an application insight, rather, they are just getting deployed like a individual resource.  Am I missing something here ?. Please let me know.

Also, in the same link, at the bottom of the section, in the Limitations : it is mentioned like "For an technical reason, this mechanism cannot be used to create workbook instances in the Workbooks gallery of Application Insights. We are working on addressing this limitation." 

Is there any updates on this limitation mentioned ? 
or How can I deploy programmatically workbook instance to an application insight. 

Please help.

Thank you.

**Comment by gardnerjr** [comment]
@ericc1103  is actively working on removing this limitation for application insights workbooks.

creating things via an arm template does create them as individual resources. the `workbookSourceId` / `workbookSourceId` in that sample is what "links" the tsg/workbook you just created to the application insights resource.  If that is done properly, you'll see the item show up in the saved list for that resource.

**Comment by jdebarochez** [comment]
Hello everyone,
Is there an update on this topic?
@gardnerjr what do you mean by done properly? My workbookSourceId looks like this `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.insights/components/{resourceName}`

**Comment by gardnerjr** [comment]
if your workbook type is "tsg" and your workbookSourceId is a valid azure resource id for an application insights resource, then you should see your workbook in the "Troubleshooting Guides" section of application insights.

**Comment by AntonChernysh** [comment]
@gardnerjr Does what you described above work for you?
I just tried with proper **sourceId** in workbook ARM deployment. and it's still created as an independent resource and I don't see any references to this workbook in App insights.
See my deployment template
```hcl
resource "azurerm_template_deployment" "workbook_deployment" {
  name                = "tmp-tmp-usw-infra-workbook"
  resource_group_name = module.temp_rg.resource_group_name

  template_body = <<JSON
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "variables": {
     "_force_terraform_to_always_redeploy": "${timestamp()}"
  },
  "parameters": {
    "workbookId": {
      "type": "string",
      "defaultValue": "[newGuid()]",
      "metadata": {
        "description": "The unique guid for this workbook instance"
      }
    }
  },
  "resources":[
    {
      "name": "[parameters('workbookId')]",
      "type": "microsoft.insights/workbooks",
      "location": "[resourceGroup().location]",
      "apiVersion": "2018-06-17-preview",
      "dependsOn": [],
      "kind": "shared",
      "properties": {
        "displayName": "tmp-tmp-usw-infra-workbook",
        "serializedData": "{\"version\":\"Notebook/1.0\",\"items\":[{\"type\":1,\"content\":{\"json\":\"## New workbook\\n---\\n\\nWelcome to your new workbook.  This area will display text formatted as markdown.\\n\\n\\nWe've included a basic analytics query to get you started. Use the `Edit` button below each section to configure it or add more sections.\"},\"name\":\"text - 2\"},{\"type\":3,\"content\":{\"version\":\"KqlItem/1.0\",\"query\":\"union withsource=TableName *\\n| summarize Count=count() by TableName\\n| render barchart\",\"size\":1,\"queryType\":0,\"resourceType\":\"microsoft.insights/components\"},\"name\":\"query - 2\"}],\"isLocked\":false}",
        "version": "1.0",
        "sourceId": "/subscriptions/my-subscription-id-here/resourceGroups/tmp-tmp-usw-infra-rg/providers/Microsoft.Insights/components/tmp-tmp-usw-infra-ai",
        "category": "workbook"
      }
    }
  ]


}
JSON

deployment_mode = "Incremental"
}
```
of course I'm replacing **my-subscription-id-here** with real value

**Comment by gardnerjr** [comment]
remember: https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Programmatically.md#limitations:  has this in the limitations section:
> this mechanism cannot be used to create workbook instances in the Workbooks gallery of Application Insights

above, it looks like you are trying to create a workbook inside application insights (i see `category:workbook` and `sourceId:.../providers/microsoft.insights/components...` , which isn't supported.  you could deploy in to the "tsg" or "usage"  workbook category inside application insights and you'd see them there (under "investigate > troubleshooting guide" or "usage > more")

**Comment by krishna1s** [comment]
Hi @gardnerjr 

I was trying to deploy it over AKS resource workbook

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workbookDisplayName":  {             
            "type":"string",
            "defaultValue": "My Workbook",
            "metadata": {
                "description": "The friendly name for the workbook that is used in the Gallery or Saved List. Needs to be unique in the scope of the resource group and source" 
            }
        },
        "workbookType":  {             
            "type":"string",
            "defaultValue": "workbook",
            "metadata": {
                "description": "The gallery that the workbook will been shown under. Supported values include workbook, tsg, Azure Monitor, etc." 
            }
        },
        "workbookSourceId":  {             
            "type":"string",
            "defaultValue": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.ContainerService/managedClusters/{aksClusterName}",
            "metadata": {
                "description": "The id of resource instance to which the workbook will be associated" 
            }
        },
        "workbookId": {
            "type":"string",
            "defaultValue": "[newGuid()]",
            "metadata": {
                "description": "The unique guid for this workbook instance" 
            }
        }
    },    
    "resources": [
        {
            "name": "[parameters('workbookId')]",
            "type": "Microsoft.Insights/workbooks",
            "location": "[resourceGroup().location]",
            "kind": "shared",
            "apiVersion": "2018-06-17-preview",
            "dependsOn": [],
            "properties": {
                "displayName": "[parameters('workbookDisplayName')]",
                "serializedData": "{\"version\":\"Notebook/1.0\",\"items\":[{\"type\":1,\"content\":\"{\\\"json\\\":\\\"Hello World!\\\"}\",\"conditionalVisibility\":null}],\"isLocked\":false}",
                "version": "1.0",
                "sourceId": "[parameters('workbookSourceId')]",
                "category": "[parameters('workbookType')]"
            }
        }
    ],
    "outputs": {
        "workbookId": {
            "type": "string",
            "value": "[resourceId( 'Microsoft.Insights/workbooks', parameters('workbookId'))]"
        }
    }
}

It is still deploying it as a individual resource. What things need to change, if we want to see under workbook section of AKS ?

or Is it not possible to deploy workbook under a workbook gallery of a resource

**Comment by Nikolay-Uvarov** [comment]
Does anyone know a workaround for deploying the workbook with "workbook" type not "tsg"? 
Thanks

**Comment by gardnerjr** [comment]
the workarounds are listed above: use `tsg` or use `usage` if you want to deploy ARM based workbooks for application insights.  We're still working on removing this limitation but trying to avoid migrating all of the existing legacy "favorites" based application insights workbooks which are not full ARM resources like microsoft.insights/workbooks are.

**Comment by SergiiGalai** [comment]
Issue is closed. No reason, no comment, no pull request.
What's the reason of closing the issue if it is still not resolved? If it won't be fixed, why not at least change the message in /Documentation/Programmatically.md "For an technical reason, this mechanism cannot be used to create workbook instances in the Workbooks gallery of Application Insights. We are working on addressing this limitation."...

**Comment by gardnerjr** [comment]
It was closed because it is a well known and well documented limitation, with documented workarounds.  

The documentation is correct, we are working on it, but it hasn't been completed yet, and has been blocked by other things.
