### ISSUE TITLE
Workbook Retrieval Tool does not work

### ISSUE THREAD

**Issue by bbbbbbbs** [microsoft/Application-Insights-Workbooks#2015]
PrivateWorkbookConversion.workbook code/tool does not show any private workbooks under any subscription or resources. "No private workbooks found".  Please help. Thanks

**Comment by gardnerjr** [comment]
@bbbbbbbs need more info than that.  The private workbook tool is querying private workbooks which belong to you in those locations.  if it doesn't show any, there might not be any?

Do you know that you do have private workbook (myworkbook) resources? 

This is different from "legacy" workbooks that are inside application insights resources, there's separate instructions for those.
