### ISSUE TITLE
add samples for dropdown with selection, grouping

### ISSUE THREAD

**Issue by gardnerjr** [microsoft/Application-Insights-Workbooks#202]
https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Parameters/DropDown.md

there are samples there for json, query dropdowns, but they don't explain the "advanced" behaviors for 

column 0 = value, column 1 = name, column 2 = selected, column 3 (or named "group") = group

which applies to all of the various dropdowns.

**Comment by oveiyakrish** [comment]
Very good brief and this post helped me a lot. Say thank you I searching for your facts. Thanks for sharing with us!
https://www.gangboard.com/business-intelligence-training/qlik-sense-training?utm_source=socials&utm_medium=fb&utm_campaign=coursepage&utm_term=qlik&utm_content=oveiya

**Comment by gardnerjr** [comment]
(deleted comment spam)

**Comment by gardnerjr** [comment]
There are examples of this now, not sure why i didn't close this issue earlier.
