### ISSUE TITLE
Backup Report  - Azure Files backups not displaying Cloud Storage Space

### ISSUE THREAD

**Issue by bsonnek** [microsoft/Application-Insights-Workbooks#2057]
The Backups report workbook is not showing us Azure Files backup vault storage consumed data. We're able to see all the other details built into the workbook for Azure Files, but for some reason the "Cloud Storage (GB)" field does not populate data. 

I've checked multiple subscriptions, and verified Log Analytics diagnostics are configured to this guide - https://learn.microsoft.com/en-us/azure/backup/configure-reports

Is anyone else seeing this issue?
Here is an image. 
![image](https://user-images.githubusercontent.com/10324197/200056563-0f9ea24d-31d0-471c-bf5f-9477b14e9b84.png)

![image](https://user-images.githubusercontent.com/10324197/200056686-3f9ff4fd-f0c7-4862-9d52-d7f59fdb898e.png)

**Comment by adityabalaji-msft** [comment]
Backup Reports shows the storage that is consumed in the Recovery Services vault. for Azure Files backup, since currently only snapshot tier backup is available and data is not transferred to the vault, the vault storage corresponding to Azure Files backup is shown as zero in the reports

**Comment by bsonnek** [comment]
HI Adi, Thank you for the response. Do you know of any method to track the storage/consumption and billable cost of Azure files backups/snapshots? We manage many customer subscriptions and are looking for a way to visualize the cost of storage. I know Microsoft is billing us for Azure files backups/snapshots, so there must be value somewhere we can grab.

**Comment by adityabalaji-msft** [comment]
There is a metric FileShareSnapshotSize availalable for Azure files: https://learn.microsoft.com/azure/azure-monitor/essentials/metrics-supported#microsoftstoragestorageaccountsfileservices
Could you review the above link and if it meets your requirement?

**Comment by bsonnek** [comment]
Thank you for the suggestion. I'll look around in the powershell commands to see what kinds of custom log value we can create in a Log Analytics workspace. We'd like to see these backup detail values in a custom azure monitor workbook to track backup consumption at scale. 

I'll close this out at this time. Thank you for answering my question and providing a recommendation.
