### ISSUE TITLE
Hotfix Deployment for SapMonitor2.0 workbooks

### ISSUE THREAD

**Issue by M2skills** [microsoft/Application-Insights-Workbooks#2210]
Hi Team,
we have pushed a hotfix for our workbook templates. this hotfix needs to be deployed faster than the usual SDP cycle since the issue is blocking the functionality for creating alerts in our service.
We have ~70 active customer subscriptions affected by this, It will be a blocker to the adoption of our product and also affect the functionality of existing alerts.

Below is the PR with the fix: https://github.com/microsoft/Application-Insights-Workbooks/pull/2209
Please let us know how we can get this hotfix deployed soon.
Thanks.

**Comment by gardnerjr** [comment]
Hotfix was done Friday (also any deployments starting after 2209 have the fix)
