### ISSUE TITLE
Do workbooks have support for pulling data from Azure SQL DB's?

### ISSUE THREAD

**Issue by riktim97** [microsoft/Application-Insights-Workbooks#2363]
Can we query SQL server db the way we can do in Power BI's with sql query to pull data from the db's?

**Comment by gardnerjr** [comment]
Currently, no.  with SOME sql server instances that support AAD auth, it might be possible for us to enable, but for SQL dbs that have any other kind of auth, it won't work the way workbooks works (it is only a client side feature of the azure portal, there's no place for us to add that extra auth layer, we can only do what the Azure portal's auth allows.
