### ISSUE TITLE
Contributor Access Request - Dell employee collaboration

### ISSUE THREAD

**Issue by paulbarry-dell** [microsoft/Application-Insights-Workbooks#2536]
I am requesting contributor access as a Dell employee.
Pull request would contain 2 items, a new Cluster.workbook file and its entry in hci insights gallery as follows: 

New Cluster.workbook
+ Application-Insights-Workbooks\Workbooks\Azure Stack HCI\Dell\SingleCluster\Cluster.workbook

HCI Insights gallery entry
+ Application-Insights-Workbooks\gallery\hci-insights\microsoft.azurestackhci-clusters.json

This work is a collaboration I have been working on between Dell and Microsoft (Saniya Islam and Sayandeep Ghosh).
I understand I will need to sign a CLA.

**Comment by gardnerjr** [comment]
@paulbarry-dell The simplest way is to fork the repo, do your work in the fork, and then create a PR from the fork into the repo.  It shouldn't require any special setup on either side.

But for now, i've added your specific user to the repo with write access to create branches and PRs directly.  all of the CLA things are handled by a github / microsoft bot  in the PR when you try to contribute.
