### ISSUE TITLE
Resource parameter names cannot be set using label

### ISSUE THREAD

**Issue by neilculver** [microsoft/Application-Insights-Workbooks#2576]
I am following the [documentation here](https://github.com/microsoft/Application-Insights-Workbooks/blob/master/Documentation/Parameters/Resources.md#creating-a-resource-parameter-using-azure-resource-graph) to create a resource parameter. The parameter needs to hold log analytics workspaces for use in workbook queries. The workspace name isn't that useful as it's been auto generated so I'd like to replace it with something more useful.

## Trying the documented approach
Renaming sounds possible by using a column named _label_ in the result set. Based on the documentation I would expect the test query below to give me a list with everything named _x_.

![image](https://github.com/microsoft/Application-Insights-Workbooks/assets/12610962/cc6956a4-17ed-4660-a59e-5ba893481f96)

But in the drop down, the resources names are still shown unmodified.

![image](https://github.com/microsoft/Application-Insights-Workbooks/assets/12610962/23e2cfdf-b862-4ee1-9af2-528e0ae294b9)

## Note on parameter order
If I modify the query to change the position, it now seems to rename as expected but the parameter doesn't work in queries. Adding some debug text, I can see that both the _value_ and _label_ have been changed to just _x_.

![image](https://github.com/microsoft/Application-Insights-Workbooks/assets/12610962/72d095b9-ae1b-4755-8018-a5d3656711a5)

![image](https://github.com/microsoft/Application-Insights-Workbooks/assets/12610962/0371be25-533a-4bff-b46c-2e3968f47cf8)

It doesn't seem to matter what the first column is called, this is always used as the _value_ and then it seems like the _label_ is derived from it (using the resource name if the first column is a resource ID).

**Comment by gardnerjr** [comment]
For now, this as designed: *resource* parameters get their names from the resources themselves, you can't override them with custom labels.  this is for security purposes to avoid people spoofing the names of resources.

as the warning says:
> When using a Resource picker, the query should return the first column of Resource picker Id values, which are expected to be Azure Resource Id values. Additional columns 'selected' and 'group' are supported. Any other data will be ignored.

![image](https://github.com/microsoft/Application-Insights-Workbooks/assets/10158007/85acea3c-4334-49b8-a963-bdf4010451fb)

if you return any other invalid data in column 0, the value is still treated as an azure resource id, and if it isn't valid, it is passed along as is.  so in this case, your 'x' values are all not valid resource ids so the values are passed along as is.

there's a current active feature request to allow whatever is in the label field to be ADDED to the resource picker, like

resourcename1 (whatever was in label column)
resourcename2 (whatever was in label column)
resourcename3 (whatever was in label column)

but it hasn't been approved or prioritized yet.

As a workaround it is possible to return custom values in the "group" field after selected column, we've suggested that to some teams that wanted to add region/location or another tag like prod/test/dev to resource names.
