### ISSUE TITLE
Reuse Custom Endpoint Settings

### ISSUE THREAD

**Issue by Panda-Sharp** [microsoft/Application-Insights-Workbooks#2643]
Hello,

Apologize in advance if I'm not writing in the right repo, if so, please feel free to redirect me.

Recently I started to work with workbooks, and I'm trying to implement a dashboard that make several calls to ADO rest endpoints, is there any way to share the base config like:

- Base url, eg: https://dev.azure.com/ORG/PROJ
- Headers, eg: authorization ...
- Query Params, eg: api-version ...

across every query, instead of redeclare everything every time? 

something like these Grafana data sources can do:
- https://grafana.com/docs/plugins/marcusolsson-json-datasource/latest/
- https://grafana.com/docs/plugins/yesoreyeram-infinity-datasource/latest/

Thanks

**Comment by gardnerjr** [comment]
@panda-sharp while not the same as grafana, you could declare those things as parameters, and mark them hidden so they don't display in read mode, and then reference the parameters in the configuration of the individual steps

**Comment by Panda-Sharp** [comment]
@gardnerjr thanks for your reply, that's what I managed to do meanwhile ... so looks like there is no better way, at least for now :)
