### ISSUE TITLE
Broken links in the SPA performance workbook

### ISSUE THREAD

**Issue by mrbullwinkle** [microsoft/Application-Insights-Workbooks#437]
The [Single Page Applications Workbook](https://github.com/microsoft/Application-Insights-Workbooks/blob/84061db588a6536454ecd2ef2a562e6e6abc7b90/Workbooks/Performance/Single%20Page%20Application%20Insights/Single%20Page%20Application%20Website%20Insights.workbook) has a broken link for "React based sites" and for "Angular based sites". Both links currently return a 404.

**Comment by pizzaz93** [comment]
#1720 by @yves-chan deprecated this workbook and removed those links
