### ISSUE TITLE
Kusto Query in Log Analytics

### ISSUE THREAD

**Issue by srikanth3300** [microsoft/Application-Insights-Workbooks#712]
We have a below kusto query in log analytics work books for azure data factory .

now we need a kusto query for each activity of the pipeline and also it should display error message 

Could you please help me put 

let data = ADFTriggerRun
| where TimeGenerated {TimeRange}
| where Status != "Running" and Status !contains "Waiting"
| where TriggerName contains "_isd_"
| where ResourceId contains "ESWFDHYUT01";
data
    | summarize LastTriggerTime = max(TimeGenerated) by TriggerName
| join kind = leftouter
(
    data
    | summarize LastTriggerStatus = max(Status) by TriggerName,TimeGenerated
)
on TriggerName,  $left.LastTriggerTime == $right.TimeGenerated
| join kind = leftouter
(
    data
    | summarize RunCount = count() by TriggerName
) 
on TriggerName
| join kind = leftouter
(
    data
    | where Status == "Succeeded"
    | summarize SuccessCount = count() by TriggerName
)
on TriggerName
| join kind = leftouter
(
    data
    | where Status == "Failed"
    | summarize FailCount = count() by TriggerName
)
on TriggerName
| join kind = leftouter
(
    data
    | where Status == "Cancelled"
    | summarize CancelCount = count() by TriggerName
)
on TriggerName
| project  TriggerName, RunCount, SuccessCount, FailCount,CancelCount,LastTriggerTimeUTC = LastTriggerTime,LastTriggerTimeIST = LastTriggerTime + 5h + 30m ,LastTriggerStatus
| order by LastTriggerStatus asc,TriggerName asc;

**Comment by gardnerjr** [comment]
what *specifically* do you need help with? the query above seems to be very specific to some resources?  Are you trying to create a generic template that others can use with a similar query in it?

**Comment by srikanth3300** [comment]
Hi John,

That query has some predefined columns , we want to know that where can we
see the table which has the resources in workbook .

**Comment by gardnerjr** [comment]
To see the all the tables available in the workspace, all the columns of the tables, and other schema info, navigate to the full "Logs" query blade, which is available from the query in workbooks in edit mode, in the right hand toolbar on the query itself:
![image](https://user-images.githubusercontent.com/10158007/80033454-a02b1300-84a1-11ea-93e4-658b2ef7ba92.png)

that blade has a full query editing experience with schema info:
![image](https://user-images.githubusercontent.com/10158007/80033615-e3858180-84a1-11ea-91c5-4927e4d320fd.png)

**Comment by gardnerjr** [comment]
@srikanth3300  let me know if there's anything else you need.
