### ISSUE TITLE
Pins for Azure backup reports not working

### ISSUE THREAD

**Issue by alishavez7** [microsoft/Application-Insights-Workbooks#722]
Hi Guys,

I enabled the vault diagnostic settings with new resource specific mode and integrated it with Log Analytics and now i am able to see the backup reports but when i pin the report to azure dashboard then widget is pinned but no data displays on it. Get the below error on widget:

This query could not run because some parameters are not set.
Please set: JobOperation, JobStatus, JobFailureCode, ContainerNameWithBackupItemName, JobMetricSortBy, JobMetricOrder, JobMetricRowsPerGrid, JobMetricPageNumber

Could anyone help me in this?

Thanks,
Shavez Ali

**Comment by gardnerjr** [comment]
that's interesting and not correct, i will investigate.

**Comment by alishavez7** [comment]
Thanks John for your response.

Just to add one thing here that only one workbook from summary page is working as expected.

**Comment by gardnerjr** [comment]
found and fixed in the portal extension: Pull Request 2859752: #7085945 - fix pins from groups not having params properly set

was occurring for anything that was inside a group control.  presuming things go well, should be deployed to prod starting Tuesday.

**Comment by alishavez7** [comment]
Thanks John, We will wait till Tuesday for you to deploy the fix in Prod.

**Comment by ericajlin** [comment]
The issue has been deployed to Prod, hence closing this issue. Please re-open if the issue persists.
