### ISSUE TITLE
 change backup reports widget names on Azure dashboard.

### ISSUE THREAD

**Issue by alishavez7** [microsoft/Application-Insights-Workbooks#752]
Hi John,

Hope you are doing good.

I have pinned number of backup reports widgets to azure dashboard but some widgets have meaningful name and some are showing Workbook so i want to change the widget names n azure dashboard.

**Comment by gardnerjr** [comment]
This is a good idea, that isn't directly possible today.  We have further down the list a way to edit the query/etc of a pin, but that's a lot of work. the ability to change the title by itself is a simpler task.  i've added an internal story to track this:

Product Backlog Item 7208272: Workbooks: add ability to edit title of workbook pins

**Comment by alishavez7** [comment]
Hi John,

Thanks for your response. 

7208272: Workbooks: add ability to edit title of workbook pins? Is it a reference Doc which i could follow to change the Workbook title/names. I am unable to locate it. Please help.

**Comment by alishavez7** [comment]
Hi John,

Any update on my previous comment?
