### ISSUE TITLE
change backup reports widget names on Azure dashboard.

### ISSUE THREAD

**Issue by alishavez7** [microsoft/Application-Insights-Workbooks#760]
Hi John,

Regarding the original issue #752 which is closed.

7208272: Workbooks: add ability to edit title of workbook pins? Is it a reference Doc which i could follow to change the Workbook title/names. I am unable to locate it. Please help.

**Comment by gardnerjr** [comment]
as i stated in that item:

> This is a good idea, that isn't directly possible today. We have further down the list a way to edit the query/etc of a pin, but that's a lot of work. the ability to change the title by itself is a simpler task. i've added an internal story to track this:
>
> Product Backlog Item 7208272: Workbooks: add ability to edit title of workbook pins

1) it isn't possible today: the author of the template can set initial values if they properly set titles on grids/charts in the template, but there's no way for a user to edit this on a dashboard)
2) i've added a story to our backlog to implement this feature.  the number won't be directly useful for you, but is useful for our tracking.
