### ISSUE TITLE
Icon Issue: "Normal" icon is displaying the icon for "informational"

### ISSUE THREAD

**Issue by scautomation** [microsoft/Application-Insights-Workbooks#770]
When selecting an icon threshold for "normal" it displays an i with a circle, but in the workbook it displays the same blue icon for informational.

**Comment by gardnerjr** [comment]
This appears to be fixed already, not sure how i missed this issue here!

![image](https://user-images.githubusercontent.com/10158007/96902578-8b780980-1449-11eb-9ca3-59d002da7570.png)
