### ISSUE TITLE
HANA DB log backup jobs.

### ISSUE THREAD

**Issue by alishavez7** [microsoft/Application-Insights-Workbooks#788]
Hi John / Team,

Does azure backup reports support hana db log backup jobs? I am able to monitor the hana db full backup jobs but not the log backup success/failed jobs.

Please assist how we could incorporate the hana db log backup jobs with backup reports.

Thanks

**Comment by alishavez7** [comment]
Hi Team,

Any update on this?

**Comment by alishavez7** [comment]
Hi Team,

Any update on this? It's pending since last 27 days and still no response.

Thanks,
Shavez Ali

**Comment by acearun** [comment]
@VinothJeyaraman can you help with this issues please?

**Comment by VinothJeyaraman55** [comment]
Hi alishavez7,

@adityabalaji-msft .. to your notice
In Backup Report, we dont expose log backup jobs.
However you could directly query  the same from your loganalytics workspace.

In future, we will make the Backup Report editable. With that, you would be able to edit the queries to include log backup jobs in the reports.

Thanks.

**Comment by alishavez7** [comment]
Thanks for your response @VinothJeyaraman55
