### ISSUE TITLE
Converting view designer dashboards to workbooks

### ISSUE THREAD

**Issue by NanoMS** [microsoft/Application-Insights-Workbooks#862]
Hello, I was using this github to implement dashboards via the soon deprecated view designer of azure monitor https://github.com/MicrosoftDocs/azure-docs/commits/master/articles/firewall/log-analytics-samples.md
The feature being now replaced by workbooks is there some work planned in order to produce workbooks on azure firewall or is there any way to transit easily from .omsview to .workbook without having to manually reconstruct ?
For now the most fitted alternative I found is to monitor the azure firewall via sentinel and the workbooks developed for it like for example https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/AzureFirewall.json but any other suggestion is welcomed

**Comment by gardnerjr** [comment]
@austonli do you have any other details for migrating?

**Comment by austonli** [comment]
> Hello, I was using this github to implement dashboards via the soon deprecated view designer of azure monitor https://github.com/MicrosoftDocs/azure-docs/commits/master/articles/firewall/log-analytics-samples.md
> The feature being now replaced by workbooks is there some work planned in order to produce workbooks on azure firewall or is there any way to transit easily from .omsview to .workbook without having to manually reconstruct ?
> For now the most fitted alternative I found is to monitor the azure firewall via sentinel and the workbooks developed for it like for example https://github.com/Azure/Azure-Sentinel/blob/master/Workbooks/AzureFirewall.json but any other suggestion is welcomed

We have some templates available in LA workspaces to get you started. If you have all the queries you want to run, all you need to do is paste in the queries into the template and you can save that as a workbook for yourself.

**Comment by gardnerjr** [comment]
Given Auston's comments, i'm going to close this issue.  If you need more details feel free to reopen.
