### ISSUE TITLE
REST API or Azure CLI support for deploying the workbook

### ISSUE THREAD

**Issue by Kumar-Ashwin-Hubert** [microsoft/Application-Insights-Workbooks#916]
Is there any REST API or dedicated azure CLI commands that can help in the deployment of the workbook. 
[Workbook deployment](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/workbooks-automate) mentions ARM deployment, but maintaining a huge "serializedData" in the arm template is nowhere practical.

**Comment by gardnerjr** [comment]
There are, at this time, no dedicated azure CLI commands, though the standard create/etc commands should work for workbook and workbook template resources presuming you pass the right information and metadata.

Unfortunately, the content of the workbook _is_ that `serializedData` field, and it probably isn't anything that will change soon.  We are open to submissions though, so if you create any tooling/scripts/etc that work for your scenario and might be useful for others, let us know.

**Comment by krishna1s** [comment]
Hi @gardnerjr 

I was trying to deploy it over AKS resource workbook

{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "workbookDisplayName":  {             
            "type":"string",
            "defaultValue": "My Workbook",
            "metadata": {
                "description": "The friendly name for the workbook that is used in the Gallery or Saved List. Needs to be unique in the scope of the resource group and source" 
            }
        },
        "workbookType":  {             
            "type":"string",
            "defaultValue": "workbook",
            "metadata": {
                "description": "The gallery that the workbook will been shown under. Supported values include workbook, tsg, Azure Monitor, etc." 
            }
        },
        "workbookSourceId":  {             
            "type":"string",
            "defaultValue": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.ContainerService/managedClusters/{aksClusterName}",
            "metadata": {
                "description": "The id of resource instance to which the workbook will be associated" 
            }
        },
        "workbookId": {
            "type":"string",
            "defaultValue": "[newGuid()]",
            "metadata": {
                "description": "The unique guid for this workbook instance" 
            }
        }
    },    
    "resources": [
        {
            "name": "[parameters('workbookId')]",
            "type": "Microsoft.Insights/workbooks",
            "location": "[resourceGroup().location]",
            "kind": "shared",
            "apiVersion": "2018-06-17-preview",
            "dependsOn": [],
            "properties": {
                "displayName": "[parameters('workbookDisplayName')]",
                "serializedData": "{\"version\":\"Notebook/1.0\",\"items\":[{\"type\":1,\"content\":\"{\\\"json\\\":\\\"Hello World!\\\"}\",\"conditionalVisibility\":null}],\"isLocked\":false}",
                "version": "1.0",
                "sourceId": "[parameters('workbookSourceId')]",
                "category": "[parameters('workbookType')]"
            }
        }
    ],
    "outputs": {
        "workbookId": {
            "type": "string",
            "value": "[resourceId( 'Microsoft.Insights/workbooks', parameters('workbookId'))]"
        }
    }
}

It is still deploying it as a individual resource. What things need to change, if we want to see under workbook section of AKS ?

or Is it not possible to deploy workbook under a workbook gallery of a resource
