### ISSUE TITLE
Parameterize resource references from Kusto queries in ARM template

### ISSUE THREAD

**Issue by GuusRaaphorst** [microsoft/Application-Insights-Workbooks#945]
Hey,

I have created a workbook which contains some kusto queries that reference my application insights through a parameter. ![workbook parameter](https://user-images.githubusercontent.com/34499133/93752534-18d3fe00-fbff-11ea-931a-86aaaf9e5093.PNG)
This looks something like this in the gallery template json:

```
      "id": "97c8b655-3fa7-4fdd-be92-1fa391c35b61",
      "version": "KqlParameterItem/1.0",
      "name": "Application",
      "value": "/subscriptions/xxxx/resourceGroups/yyyy/providers/Microsoft.Insights/components/zzzzz",
      "typeSettings": {"resourceTypeFilter": {"microsoft.insights/components": true} }
```
            
This parameter is then used in the query something like this:

```
  "content": {
    "version": "KqlItem/1.0",
    "query": "<query removed for brevity> ",
    "title": "Some title", 
    "queryType": 0,
    "resourceType": "microsoft.insights/components",
    "crossComponentResources": ["{Application}"]
``` 

When I now generate an ARM template for my workbook, the parameter value  (e.g /subscriptions/xxxx/...) will be part of the serializedData in the resource "microsoft.insights/workbooks". Is there any possibility that I can supply the parameter value through the parameters of the ARM template? I like to deploy this workbook for several (similar) resource groups, where I would like to supply the application insights it needs to use for queries.

Note that I already tried to replace the value with a reference in ARM style (e.g. through [parameters('aaaa')]), but that does not work. The ARM deploy does not validate (likely because it is is part of some serializedData ) and the deployed workbook did not find the parameter. 

Is there anything I can use to get this done? My fallback scenario is to create a script to replace the values just before deploy, but I rather use an easier and more generic solution.

**Comment by gardnerjr** [comment]
you *can* do this via arm parameters, but it does become rather complicated in that you need to use concat/etc in the template to break up those values.  

In general, the way to go is to remove all the `value`, `crossComponentResources` fields like that from the content before turning it into a template.  The build tooling here does tests to check for things like that, you could clone the repo and run the tools against your template content if you wanted to do those same kinds of checks.  You can also do this by editing the json to remove those fields and pressing apply, and if your workbook still works there, it will work as a template.

Inside the resource parameters, there's a "workbook resources" option that allows you to get the current workbook resources, which you can then filter down by type if necessary.  By default, the workbook will then "inherit" the resources it has from the place that opens it, so as long as the opener is passing in those resources. 

We've investigated doing something like this in the UI itself, to "templatize" a workbook , but it hasn't bubbled to the top anywhere, and it probably wouldn't go as far as to generate ARM template specific parameter replacements inside the content.

If this is something you do often, it probably would be possible to create a script that does that string manipulation to your specific needs?
