### ISSUE TITLE
Workbook: Workspace Usage error

### ISSUE THREAD

**Issue by pejuborg** [microsoft/Application-Insights-Workbooks#962]
Hi,
I'm trying to run the Workspace Usage workbook from my Log Analytics workspace, but I'm getting an error:

`union: column named 'TableName' already exists
Click to Retry. 
`

I've tried to edit the query but since my knowledge is lacking I cannot fix this myself, hence this issue.

**Comment by gardnerjr** [comment]
yes, someone has apparently added a column named `TableName` somewhere in the schema, so the union function fails.

see #966 for a fix.  there are a few templates scattered around with this issue
